### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by zxchidden** [in9lude/line#3]
after login with qr always "logout"

is there someone can fix it?

**Comment by WEDeach** [comment]
LINE updated some of the code, use the QRC login will receive "LOG_OUT"

**Comment by hiiwave** [comment]
I used to be able to login, but not now either.
My authtoken has expired. When I try `line = LineClient()` and open the authorization link on smartphone, it throws `TalkException(code=8, reason='LOG_OUT', parameterMap=None)` as well.
Any suggestion?

**Comment by in9lude** [comment]
I have solved the problem but won't disclose solution.
